export const DEFAULTS = {
  dark: {
    background: "#09090b",
    foreground: "#c8c8d0",
    cursorColor: "#d4d4dc",
    cursorText: "#09090b",
    selectionBg: "#2a2a35",
    selectionFg: "#e0e0e8",
    palette: [
      "#16161e",
      "#e0a0a0",
      "#a0d4a0",
      "#ddc890",
      "#90b8e0",
      "#c8a8e0",
      "#88c8d8",
      "#c8c8d0",
      "#2a2a35",
      "#f0baba",
      "#b8e4b8",
      "#e8d8a8",
      "#aacce8",
      "#d8bfe8",
      "#a4d8e4",
      "#e8e8f0",
    ],
  },
  light: {
    background: "#e8e8ed",
    foreground: "#2a2a32",
    cursorColor: "#3a3a44",
    cursorText: "#e8e8ed",
    selectionBg: "#c4c4ce",
    selectionFg: "#1e1e26",
    palette: [
      "#2a2a32",
      "#a03848",
      "#2e7d46",
      "#8a6518",
      "#2868b0",
      "#7844a8",
      "#1a7888",
      "#d0d0d8",
      "#3e3e48",
      "#882830",
      "#1e6e36",
      "#745510",
      "#1858a0",
      "#683898",
      "#0e6878",
      "#e8e8ed",
    ],
  },
}

export const NAMES = [
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  "bright black",
  "bright red",
  "bright green",
  "bright yellow",
  "bright blue",
  "bright magenta",
  "bright cyan",
  "bright white",
]

export const FONTS = [
  { label: "Default (system)", value: "" },
  { label: "JetBrains Mono", value: "JetBrains Mono" },
  { label: "Fira Code", value: "Fira Code" },
  { label: "Cascadia Code", value: "Cascadia Code" },
  { label: "Source Code Pro", value: "Source Code Pro" },
  { label: "IBM Plex Mono", value: "IBM Plex Mono" },
  { label: "Iosevka", value: "Iosevka" },
  { label: "Hack", value: "Hack" },
  { label: "Inconsolata", value: "Inconsolata" },
  { label: "Victor Mono", value: "Victor Mono" },
  { label: "Monaspace Neon", value: "Monaspace Neon" },
  { label: "Monaspace Argon", value: "Monaspace Argon" },
  { label: "Berkeley Mono", value: "Berkeley Mono" },
  { label: "Commit Mono", value: "Commit Mono" },
  { label: "Geist Mono", value: "Geist Mono" },
  { label: "SF Mono", value: "SF Mono" },
  { label: "Monaco", value: "Monaco" },
  { label: "Menlo", value: "Menlo" },
  { label: "Consolas", value: "Consolas" },
]
